import PDFDocument from "pdfkit";

export const generateAssessmentPDF = (assessmentData, res) => {
  const doc = new PDFDocument({ margin: 50 });

  // Stream the PDF directly to the User (Download)
  doc.pipe(res);

  // --- HEADER ---
  doc.fontSize(20).text("OrgPath Insights Report", { align: "center" });
  doc.moveDown();
  doc.fontSize(12).text(`Generated for: User #${assessmentData.user_id}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(2);

  // --- OVERALL SCORE ---
  doc.fontSize(16).text("Overall Performance Score", { underline: true });
  doc.moveDown(0.5);
  
  const score = assessmentData.details?.overall_score || 0;
  const percentage = (score * 100).toFixed(0) + "%";
  
  // Draw a "Progress Bar"
  doc.fontSize(12).text(`Score: ${percentage}`);
  doc.rect(50, doc.y, 400, 20).stroke(); // Outline
  doc.rect(50, doc.y, 400 * score, 20).fill("#4CAF50"); // Green Fill
  doc.moveDown(3);

  // --- CATEGORY BREAKDOWN ---
  doc.fillColor("black").fontSize(16).text("Category Breakdown", { underline: true });
  doc.moveDown();

  const categories = assessmentData.details?.category_scores || {};

  for (const [category, val] of Object.entries(categories)) {
    const catPercent = (val * 100).toFixed(0) + "%";
    
    doc.fontSize(12).text(`${category}: ${catPercent}`);
    
    // Mini-bar for each category
    const barWidth = 300 * val; 
    doc.rect(50, doc.y, 300, 10).stroke();
    doc.rect(50, doc.y, barWidth, 10).fill("#2196F3"); // Blue Fill
    doc.moveDown(1.5);
    doc.fillColor("black"); // Reset color
  }

  // --- FOOTER ---
  doc.moveDown(4);
  doc.fontSize(10).text("Generated by OrgPath Backend System.", { align: "center", color: "grey" });

  // Finalize the PDF
  doc.end();
};